- scripts/rackhd.py
- Allow ansible to get hosts inventory from rackHD by node id
- the ansible job looks for this script in /opt/onrack/etc/ansible/
> Add inventory script for ansible-playbook

- winpe/README.md
@RackHD/corecommitters @uppalk1 @amymullins @zyoung51 @keedya
> add the steps to set up winpe for windows install

- scripts/setup_iso.py
Update setup_iso.py script to support:
- SLES 
- Ubuntu
- PhotonOS
- Windows 2012
@RackHD/corecommitters @iceiilin @pengz1
> Update setup_iso.py script to support more OS

- obm-migration/README.md
- obm-migration/obmMigration.js
- obm-migration/package.json
Move original OBM migration script to on-tools
@brianparry @geoff-reid @srinia6 @BillyAbildgaard
> OBM migration script

- obm-migration/README.md
- obm-migration/obmMigration.js
@RackHD/corecommitters @srinia6 @BillyAbildgaard 
depends on: https://github.com/RackHD/on-core/pull/222
> Migrate SSH settings

- manifest-build-tools/lib/ParallelTasks.py
- manifest-build-tools/lib/config.py
- manifest-build-tools/lib/gitbits.py
Add library for manfiest build tools.
The proposal of manifest build in rackhd release  is [here](https://groups.google.com/forum/#!topic/rackhd/v3LpRuQJvQg).
> [manifest] #1 add library for manifest build tools

- manifest-build-tools/lib/RepositoryOperator.py
Add a module RepositoryOperator to abstract operations to repository.
The proposal of manifest build in rackhd release  is [here](https://groups.google.com/forum/#!topic/rackhd/v3LpRuQJvQg).
This PR depends on https://github.com/RackHD/on-tools/pull/25
> [manifest] #2  add a module to abstract operations to repository

- manifest-build-tools/lib/manifest.py
Add a module to abstract a manifest file
The proposal of manifest build in rackhd release  is [here](https://groups.google.com/forum/#!topic/rackhd/v3LpRuQJvQg).
This PR depends on https://github.com/RackHD/on-tools/pull/25 and https://github.com/RackHD/on-tools/pull/26
> [manifest] #3 add a module to abstract a manifest file

- manifest-build-tools/bintray.conf
- manifest-build-tools/pushToBintray.sh
Add script to push package to bintray
> [manifest] #7 add script to push package to bintray

- manifest-build-tools/application/reprove.py
- manifest-build-tools/lib/RepositoryOperator.py
- manifest-build-tools/lib/manifest.py
This PR is used for the release of rackhd.
new features:
1. create branch from a manifest file
2. update package.json to ref the new branch for each repository
@panpan0000 @changev
> create branch from a manifest file

- performance-tools/config/amqp.py
- performance-tools/config/settings.py
- performance-tools/modules/amqp.py
- performance-tools/modules/logger.py
- performance-tools/modules/worker.py
- performance-tools/performance.py
The throughput is measured in workflows/sec
> Standalone performance tool that calculates the throughput of RackHD.

- manifest-build-tools/application/update_changelog.py
Add an entry to the debian/changelog for new release.
> add a script to update the changelog for new release

- index-migration/README.md
- index-migration/indexMigration.py
1.  Remove dump* in working directory
2. Execute mongodump to backup mogodb
3. Drop all indexes from the collections of mongo db
> Add script for index migration

- manifest-build-tools/application/update_dependencies.py
- manifest-build-tools/application/update_rackhd_version.py
Update rackhd debian control according to a manifest file.
The proposal of manifest build in rackhd release  is [here](https://groups.google.com/forum/#!topic/rackhd/v3LpRuQJvQg).
This PR depends on:  https://github.com/RackHD/on-tools/pull/30
> [manifest] #6  update rackhd debian control according to a mainfest file.

- manifest-build-tools/pushToBintray.sh
**Background**
there're several category for Bintray files, example : debian package or vagrant  or generic file.
for the vagrant or generic file, there's a option called "Target Repository Path"
it's useful to upload file into different folders: example as below:
```
2016-11-18/x.txt
2016-11-19/x.txt
```
**How it's implemented**
reference: https://bintray.com/docs/usermanual/uploads/uploads_uploadingusingapis.html
NOTE: in Bintray Rest API, the file name should follow the target path. that's why I extract the basename of file and append to the URL.
@PengTian0  @changev
> add "Target Repository Path" parameter to pushToBintray.sh 

- manifest-build-tools/post_test.sh
Integrate post-test script for ova,vagrant,docker post test.
http://rackhdci.lss.emc.com/job/BuildRelease/job/Build/job/vagrant-post-test/
http://rackhdci.lss.emc.com/job/BuildRelease/job/Build/job/docker-post-test/
http://rackhdci.lss.emc.com/job/BuildRelease/job/Build/job/ova-post-test/
@panpan0000 @PengTian0
> Add post-test scripts

- obm-migration/README.md
- obm-migration/obmMigration.js
- obm-migration/package.json
Depends on
https://github.com/RackHD/on-tasks/pull/394
https://github.com/RackHD/on-core/pull/252
https://github.com/RackHD/on-http/pull/570
> SSH and SNMP migration

- dev_tools/sniff.js
Just to pretty the sniff output so as to let it be more readable.
@iceiilin @anhou @lanchongyizu @pengz1 
Below is example output:
```
graph.progress.updated.information.2aac2651-391a-4f78-8c27-7ceeba13b003.58806ad176fab9d82b831e4a
{
"type": "graph",
"action": "progress.updated",
"typeId": "2aac2651-391a-4f78-8c27-7ceeba13b003",
"nodeId": "58806ad176fab9d82b831e4a",
"severity": "information",
"data": {
"graphId": "2aac2651-391a-4f78-8c27-7ceeba13b003",
"nodeId": "58806ad176fab9d82b831e4a",
"graphName": "Install ESXi",
"progress": {
"description": "Enter profile, start to download installer",
"value": 3,
"maximum": 6,
"percentage": "50%"
},
"taskProgress": {
"taskId": "24ad50bf-14a7-4c98-a2e4-ca1dbb9128c2",
"taskName": "Install Esx",
"progress": {
"maximum": 6,
"value": 2,
"description": …
```
> pretty sniff output

- scripts/setup_iso.py
fix Photon OS mounting issue RAC-4417
> fix Photon OS mounting issue RAC-4417

- rackhd_BIST/bist_rackhd_config.json
- rackhd_BIST/test_suites.py
1) remove an unnecessary static file from the file "bist_rackhd_config.json"
2) change host and port for http config
> change rackhd_BIST script
